# Generated by Django 4.0.2 on 2022-08-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
